[tracker]
peer_timeout = "60s"
maintain_interval = "10s"
max_peers = 100
max_return_peers = 10

[peer]
dataset = "prepared_fMNIST"
update_freq = "30s"

[telemetry]
url = "http://influx:8181"
db = "btml"

[grafana]
url = "http://grafana:3000"
user = "admin"
password = "admin"
